# Generated by Django 4.0.6 on 2023-05-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeappraisalform',
            name='manager_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='employeeappraisalform',
            name='supervisor_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, null=True),
        ),
    ]
