# Generated by Django 4.0.6 on 2023-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalentry', '0002_alter_employeeappraisalform_manager_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeappraisalform',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
